#! /bin/bash

CLUP=""
DEF_TAGS="DOCKER FEDORA21"
if [ -n "$AUTO_CLEANUP" ]; then CLUP="-l"; fi

NO_COLORS=1 cloudrunner-node configure --id "$HOSTNAME" --server "$SERVER_ID" --org "$ORG_ID" $CLUP -o -t ${TAGS:-$DEF_TAGS}

NO_COLORS=1 cloudrunner-node details

NO_COLORS=1 cloudrunner-node run
